#!/usr/bin/env python3
"""Closed-loop trial campaign runner for the VRX deployment.

For every (arm, cell, seed): start Gazebo with the trial world and the canonical
spawn, the MPC with the cell parameters, the sidecar (manifold / b4 arms), and a
bag recorder; watch /wamv/thruster_health and /wamv/manifold_status; stop the
trial 180 s after the fault or on mission completion; tear everything down;
write a trial manifest. Bags and logs are named by cell and seed.

Cells: --degrade 0.5 0.95 --directions beneficial nominal --sea-state 3
Arms:  manifold b4 internal   (internal = the MPC's own planner, no sidecar)

Example (20 trials per cell, three arms):
    python ros2/run_trials.py --worlds ~/usv_ws/worlds --out ~/usv_ws/experiments \
        --arms manifold b4 internal --degrade 0.5 0.95 --n-trials 20

Requires: worlds generated by make_trial_worlds.py, the step-1 MPC build,
ROS 2 sourced, and (for the manifold arm) the trained checkpoint.
"""
import argparse
import json
import os
import signal
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

import rclpy                                            # noqa: E402
from rclpy.node import Node                             # noqa: E402
from std_msgs.msg import Float64MultiArray              # noqa: E402

TOPICS = ["/wamv/sensors/position/ground_truth_odometry", "/wamv/thrusters/left/thrust",
          "/wamv/thrusters/right/thrust", "/wamv/ref_pose", "/wamv/error_pose",
          "/wamv/control_inputs", "/wamv/ekf_pose", "/wamv/disturbance",
          "/wamv/disturbance_world", "/wamv/operational_mode", "/wamv/thruster_health",
          "/wamv/environmental_assistance", "/wamv/planning_status", "/wamv/prediction_metrics",
          "/wamv/mission_metrics", "/wamv/usv_state", "/wamv/manifold_ref",
          "/wamv/manifold_status", "/wamv/manifold_proposal", "/vrx/debug/wind/speed",
          "/vrx/debug/wind/direction", "/clock"]


class Watcher(Node):
    def __init__(self):
        super().__init__("trial_watcher")
        self.t_fault = None
        self.completed = False
        self.fallback = False
        self.latency = None
        self.create_subscription(Float64MultiArray, "/wamv/thruster_health", self.on_h, 10)
        self.create_subscription(Float64MultiArray, "/wamv/manifold_status", self.on_s, 10)

    def now(self):
        return time.time()

    def on_h(self, m):
        if self.t_fault is None and len(m.data) >= 2 and min(m.data[:2]) < 99.9:
            self.t_fault = self.now()

    def on_s(self, m):
        # [mode, ref_received, latency_s, fallback, rows, line_index, since_trigger_s, mission_completed]
        # published every solve after the fault for every ref_source (step-1 node, reviewed build)
        if len(m.data) >= 4:
            mode = int(m.data[0]); self.fallback = bool(m.data[3] > 0.5)
            if m.data[2] >= 0: self.latency = float(m.data[2])
            if self.t_fault is not None:
                if len(m.data) >= 8:
                    if m.data[7] > 0.5: self.completed = True      # strict arrival, any arm
                elif mode == 1 and m.data[1] > 0.5:                # older node: STATION_KEEPING after ref
                    self.completed = True


def start(cmd, log_path, env=None):
    f = open(log_path, "w")
    return subprocess.Popen(cmd, stdout=f, stderr=subprocess.STDOUT, start_new_session=True,
                            env=env or os.environ.copy()), f


def stop(proc, grace=10.0):
    if proc.poll() is not None:
        return
    try:
        os.killpg(proc.pid, signal.SIGINT)
        t0 = time.time()
        while proc.poll() is None and time.time() - t0 < grace:
            time.sleep(0.2)
        if proc.poll() is None:
            os.killpg(proc.pid, signal.SIGKILL)
    except ProcessLookupError:
        pass


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--worlds", required=True, help="directory with trial_ss*_<dir>_seedNNNN.sdf")
    p.add_argument("--out", default="~/usv_ws/experiments")
    p.add_argument("--spawn", default=str(Path("~/usv_ws/src/vrx/vrx_control/config/spawn_canonical_start.yaml").expanduser()))
    p.add_argument("--ref-traj", default=str(Path("~/usv_ws/src/vrx/vrx_control/traj/approach_leg_0p8.txt").expanduser()))
    p.add_argument("--ckpt", default=str(ROOT / "runs/ckpt.pt"))
    p.add_argument("--arms", nargs="+", default=["manifold", "b4", "internal"])
    p.add_argument("--degrade", nargs="+", type=float, default=[0.5, 0.95])
    p.add_argument("--fault-type", type=int, default=1)
    p.add_argument("--directions", nargs="+", default=["beneficial", "nominal"])
    p.add_argument("--sea-state", type=int, default=3)
    p.add_argument("--n-trials", type=int, default=20)
    p.add_argument("--post-fault-s", type=float, default=180.0)
    p.add_argument("--max-trial-s", type=float, default=480.0)
    p.add_argument("--settle-s", type=float, default=25.0, help="Gazebo start-up wait before the MPC")
    p.add_argument("--headless", action="store_true")
    p.add_argument("--python", default=sys.executable, help="interpreter for the sidecar (the venv)")
    a = p.parse_args()

    out = Path(a.out).expanduser(); (out / "bags").mkdir(parents=True, exist_ok=True)
    (out / "logs").mkdir(exist_ok=True); (out / "manifests").mkdir(exist_ok=True)
    rclpy.init()
    manifest_all = []
    for arm in a.arms:
        for deg in a.degrade:
            for d in a.directions:
                for k in range(a.n_trials):
                    seed = a.sea_state * 100 + (0 if d == "beneficial" else 50) + k
                    world = Path(a.worlds) / f"trial_ss{a.sea_state}_{d}_seed{seed:04d}.sdf"
                    if not world.exists():
                        print(f"missing world {world}; skipping"); continue
                    tid = f"{arm}_d{int(deg*100)}_ss{a.sea_state}_{d}_seed{seed:04d}"
                    mpath = out / "manifests" / f"{tid}.json"
                    if mpath.exists():
                        print(f"{tid}: done, skipping"); continue
                    print(f"=== {tid} ===", flush=True)
                    procs = []
                    gz_cmd = ["ros2", "launch", "vrx_gz", "competition.launch.py",
                              f"world:={str(world.with_suffix(''))}", f"config_file:={a.spawn}"]
                    if a.headless: gz_cmd.append("headless:=true")
                    procs.append(start(gz_cmd, out / "logs" / f"{tid}_gz.log"))
                    time.sleep(a.settle_s)
                    bag = out / "bags" / tid
                    procs.append(start(["ros2", "bag", "record", "-o", str(bag)] + TOPICS,
                                       out / "logs" / f"{tid}_bag.log"))
                    time.sleep(2.0)
                    if arm != "internal":
                        procs.append(start([a.python, str(ROOT / "ros2/vrx_manifold_node.py"),
                                            "--arm", arm, "--ckpt", a.ckpt, "--trial-id", tid,
                                            "--log-dir", str(out / "logs"), "--seed", str(seed)],
                                           out / "logs" / f"{tid}_sidecar.log"))
                        time.sleep(8.0)      # model + planners load before the MPC starts driving
                    ref_source = "manifold" if arm != "internal" else "internal"
                    procs.append(start(["ros2", "launch", "vrx_control", "mpc_manifold.launch.py",
                                        f"degrade:={deg}", f"fault_type:={a.fault_type}",
                                        f"ref_source:={ref_source}", f"ref_traj:={a.ref_traj}"],
                                       out / "logs" / f"{tid}_mpc.log"))
                    w = Watcher(); t_start = time.time(); reason = "max_time"
                    while time.time() - t_start < a.max_trial_s:
                        rclpy.spin_once(w, timeout_sec=0.2)
                        if w.t_fault is not None:
                            if w.completed: reason = "completed"; break
                            if time.time() - w.t_fault > a.post_fault_s: reason = "post_fault_timeout"; break
                    man = {"trial_id": tid, "arm": arm, "degradation": deg, "fault_type": a.fault_type,
                           "direction": d, "sea_state": a.sea_state, "seed": seed,
                           "world": str(world), "bag": str(bag), "stop_reason": reason,
                           "fault_seen": w.t_fault is not None,
                           "post_fault_s": (time.time() - w.t_fault) if w.t_fault else None,
                           "ref_latency_s": w.latency, "fallback": w.fallback}
                    w.destroy_node()
                    for pr, f in reversed(procs):        # bag first (flush), then nodes, then gz
                        stop(pr); f.close()
                    time.sleep(5.0)
                    mpath.write_text(json.dumps(man, indent=2)); manifest_all.append(man)
                    print(f"    -> {reason}, latency {w.latency}, fallback {w.fallback}", flush=True)
    rclpy.shutdown()
    (out / "manifests" / "all.json").write_text(json.dumps(manifest_all, indent=2))


if __name__ == "__main__":
    main()
